# -*- coding: utf-8 -*-
"""WinWin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d3wmJWroUzRGu-3qW3tF5inYqBhLkccD
"""

#Calcuadora win-win
def winWin(odd1, odd2, aposta):
    L1 = []
    L2 = []
    L2.append(odd1)
    L2.append(odd2)
    L2.sort()
    porcentagem1 = L2[0]*(100/(odd1+odd2))
    porcentagem2 = L2[1]*(100/(odd1+odd2))
    L1.append(porcentagem1)
    L1.append(porcentagem2)
    aposta1 = aposta-(aposta*(porcentagem1/100))
    aposta2 = aposta-(aposta*(porcentagem2/100))
    lucro = ((aposta2*L2[1]-aposta)+(aposta1*L2[0]-aposta))/2
    porcentagemLucro = (lucro*100)/aposta
    return f'''
    Odd {L2[1]}: Chance de vitória {porcentagem1:.2f}% | Valor a ser apostado R${aposta2:.2f}
    Odd {L2[0]}: Chance de vitória {porcentagem2:.2f}% | Valor a ser apostado R${aposta1:.2f}
    Lucro = R${lucro:.2f} | Porcentagem de Lucro = {porcentagemLucro:.2f}% '''
    
odd1 = float(input('Digite a primeira odd: '))
odd2 = float(input('Digite a segunda odd: '))
valorAposta = float(input('Digite o valor da aposta: '))
print(winWin(odd1, odd2, valorAposta))